AMORTIZATION_CHOICES = (
    ('SAC', 'SAC'),
    ('PRICE', 'PRICE'),
    ('COMUM', 'COMUM'),
)

AMORTIZATION_CHOICES_LIST = (
    AMORTIZATION_CHOICES[0][0],
    AMORTIZATION_CHOICES[1][0],
    AMORTIZATION_CHOICES[2][0]
)
