# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 18:22
from __future__ import unicode_literals

import client.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
                ('profession', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=19)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14, validators=[client.validators.validate_CPF])),
                ('hometown', models.CharField(max_length=50)),
                ('id_document', models.ImageField(upload_to='public/id_documents')),
                ('proof_of_address', models.ImageField(upload_to='public/proof_of_address')),
                ('login', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_address', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_addresses', to='client.ActiveClient')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=6)),
                ('account', models.CharField(max_length=10)),
                ('active_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.ActiveClient')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state_acronym', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
                ('active_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='client.ActiveClient')),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
                ('profession', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=19)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14, validators=[client.validators.validate_CPF])),
                ('hometown', models.CharField(max_length=50)),
                ('spouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to='client.ActiveClient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Country')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_addresses', to='client.State'),
        ),
    ]
