# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 13:23
from __future__ import unicode_literals

import client.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_address', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=6)),
                ('account', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_document', models.ImageField(upload_to='public/id_documents')),
                ('proof_of_address', models.ImageField(upload_to='public/proof_of_address')),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
                ('profession', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=19)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[client.validators.validate_CPF])),
                ('address', models.ManyToManyField(to='client.Address')),
                ('hometown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.City')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.State'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.City'),
        ),
    ]
