# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 18:50
from __future__ import unicode_literals

import client.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_address', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=6)),
                ('account', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=58)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
                ('profession', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=19)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14, validators=[client.validators.validate_CPF])),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Country')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveClient',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.Client')),
                ('id_document', models.ImageField(upload_to='public/id_documents')),
                ('proof_of_address', models.ImageField(upload_to='public/proof_of_address')),
            ],
            bases=('client.client',),
        ),
        migrations.AddField(
            model_name='dependent',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='client.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='hometown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.City'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.State'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.City'),
        ),
        migrations.AddField(
            model_name='activeclient',
            name='address',
            field=models.ManyToManyField(to='client.Address'),
        ),
        migrations.AddField(
            model_name='activeclient',
            name='login',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activeclient',
            name='spouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_spouse', to='client.Client'),
        ),
    ]
