# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimony', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patrimony.Patrimony')),
            ],
        ),
        migrations.RemoveField(
            model_name='active',
            name='patrimony',
        ),
        migrations.AddField(
            model_name='active',
            name='equivalent_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='active',
            name='active_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actives', to='patrimony.ActiveType'),
        ),
        migrations.AddField(
            model_name='active',
            name='active_manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='actives', to='patrimony.ActiveManager'),
            preserve_default=False,
        ),
    ]
