# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Arrearage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('value_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('thirteenth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vacation', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Leftover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LifeInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('redeemable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Patrimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgts', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('salable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RegularCost',
            fields=[
                ('patrimony', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patrimony.Patrimony')),
                ('home', models.DecimalField(decimal_places=2, max_digits=8)),
                ('electricity_bill', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gym', models.DecimalField(decimal_places=2, max_digits=8)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('car_gas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cellphone', models.DecimalField(decimal_places=2, max_digits=8)),
                ('health_insurance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supermarket', models.DecimalField(decimal_places=2, max_digits=8)),
                ('housekeeper', models.DecimalField(decimal_places=2, max_digits=8)),
                ('beauty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=8)),
                ('netflix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recreation', models.DecimalField(decimal_places=2, max_digits=8)),
                ('meals', models.DecimalField(decimal_places=2, max_digits=8)),
                ('appointments', models.DecimalField(decimal_places=2, max_digits=8)),
                ('drugstore', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extras', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='realestate',
            name='patrimony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimony.Patrimony'),
        ),
        migrations.AddField(
            model_name='lifeinsurance',
            name='patrimony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimony.Patrimony'),
        ),
        migrations.AddField(
            model_name='leftover',
            name='patrimony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimony.Patrimony'),
        ),
        migrations.AddField(
            model_name='income',
            name='patrimony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimony.Patrimony'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='patrimony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimony.Patrimony'),
        ),
        migrations.AddField(
            model_name='companyparticipation',
            name='patrimony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimony.Patrimony'),
        ),
        migrations.AddField(
            model_name='arrearage',
            name='patrimony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimony.Patrimony'),
        ),
        migrations.AddField(
            model_name='active',
            name='patrimony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimony.Patrimony'),
        ),
    ]
